#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book sdefaults:
title                       : Yoga Sagar # The title of the book. Will be placed in the left navbar.
description                 : Cette section du site est consacrée à mes écrits sur le yoga et l'ayurveda.
author                      : Marie-jacques BENARD  # The author of the book
email                       : mjknews@gmail.com
baseurl                     : ""
copyright                   : "2024"                # Copyright year to be placed in the footer
logo                        : logo-yogabook.png         # A path to the book logo
url                         : "https://samkhya.benard.cloud" # the base hostname & protocol for site
footer_text                 : Created by Marie-jacques BENARD



# Prise en charge multilingue
languages: ["en", "fr"]
default_lang: "fr"
lang_relative_urls: true


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - bibliography/references.bib

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org/v2/gh/mjkben/yogabook/HEAD"      # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : false   # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : ""      # The URL of Google Colab (https://colab.research.google.com)

# Thebelab settings
use_thebelab_button              : true  # If 'true', display a button to allow in-page running code cells with Thebelab
thebelab_button_text             : "Thebelab"  # The text to display inside the Thebelab initialization button
codemirror_theme                 : "abcdef"  # Theme for codemirror cells, for options see https://codemirror.net/doc/manual.html#config

# nbinteract settings
use_show_widgets_button          : true  # If 'true', display a button to allow in-page running code cells with nbinteract

# Download settings
use_download_button              : true  # If 'true', display a button to download a zip file for the notebook
download_button_text             : "Download" # The text that download buttons will contain
download_page_header             : "Made with Jupyter Book" # A header that will be displayed at the top of and PDF-printed page



#######################################################################################
# Binder link settings
use_binder_button                : true  # If 'true', add a binder button for interactive links
binderhub_url                    : "https://mybinder.org"  # The URL for your BinderHub. If no URL, use ""
binder_repo_base                 : "https://github.com/"  # The site on which the textbook repository is hosted
binder_repo_org                  : "matteoacrossi"  # The username or organization that owns this repository
binder_repo_name                 : "oqs-jupyterbook"  # The name of the repository on the web
binder_repo_branch               : "master"  # The branch on which your textbook is hosted.
binderhub_interact_text          : "Interact"  # The text that interact buttons will contain.


# Jupyterhub link settings
use_jupyterhub_button            : false  # If 'true', display a button that will direct users to a JupyterHub (that you provide)
jupyterhub_url                   : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu) If no URL, use ""
jupyterhub_interact_text         : "Interact"  # The text that interact buttons will contain.



# Information about where the book exists on the web
repository:
  url: https://github.com/mjkben/book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

#######################################################################################
# HTML-specific settings
html:
  favicon                   : ""    # A path to a favicon image
  use_edit_page_button      : false # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in

# Add GitHub buttons to your book
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  use_multitoc_numbering    : true  # Continuous numbering across parts/chapters
  google_analytics_id       : ""    # A GA id that can be used to track book views.
  home_page_in_navbar       : false # Whether to include your home page in the left Navigation Bar
  baseurl                   : ""    # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/ ou "/mon-projet" # le sous-dossier relatif à votre site, si nécessaire
  url                     : ""      # l'URL de votre site
  analytics:
  extra_navbar: |
        <div>
            Crée par <a href="https://perso.univ-lyon1.fr/marc.buffat/">Marc BUFFAT</a><br> avec <a href="https://jupyterbook.org">Jupyter Book</a>
        </div>

  extra_footer: |
        <div>
            Crée par <a href="https://samkhya.benard.cloud">Marie-jacques BENARd</a>
        </div>

  comments:
    hypothesis              : true
    utterances              : false
  # announcement              : "Cette section du site est consacrée à mes écrits sur le Yoga et l'Ayurveda." # A banner announcement at the top of the site.

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default
  # Define the name of the latex output file for PDF builds
  latex_documents:
    targetname: book.tex

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions    :       # A list of extra extensions to load by Sphinx (added to those already used by JB).
  local_extensions    :       # A list of local extensions to load by sphinx specified by "name: path" items
  recursive_update    : false # A boolean indicating whether to overwrite the Sphinx config (true) or recursively update (false)
  config              :       # key-value pairs to directly over-ride the Sphinx configuration
    language          : fr    # passe l'IHM en francais
parse_with_myst: true
exclude_patterns    :   [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints","CONDUCT.md", "markdown-notebooks.md", "notebooks.ipynb"]

html_show_copyright: false
myst_amsmath_enable: true
# html_theme: sizzle
html_theme: monokai


#######################################################################################
# extended html
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - html_admonition
    - html_image
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true          # Allow display math ($$) within an inline context


#######################################################################################
# Jupyter book settings you probably don't need to change
only_build_toc_files      : true
content_folder_name       : "content"  # The folder where your raw content (notebooks/markdown files) are located
images_url                : "/assets/images" # Path to static image files
css_url                   : "/assets/css" # Path to static CSS files
js_url                    : "/assets/js" # Path to JS files
custom_static_url         : "/assets/custom" # Path to user's custom CSS/JS files
use_jupyterhub_button     :  false   # Si 'true', affichez un bouton qui dirigera les utilisateurs vers un JupyterHub (que vous fournissez)

# Sidebar settings
show_sidebar              : false  # Show the sidebar. Only set to false if your only wish to host a single page.
collapse_inactive_chapters: false  # Whether to collapse the inactive chapters in the sidebar
collapse_inactive_sections: false  # Whether to collapse the sub-sections within a non-active section in the sidebar
# textbook_logo             : images/oqs.001.png  # A logo to be displayed at the top of your textbook sidebar. Should be square
textbook_logo_link        : index.html  # A link for the logo.
sidebar_footer_text       : 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'
number_toc_chapters       : true  # Whether to add numbers to chapterse in your Table of Contents. If true, you can control this at the Chapter level in _data/toc.yml

# Search settings
search_max_words_in_content : 100  # In the search function, use at most this many words (too many words will make search slow)

# # Controlling page information
page_titles                    : toc  # Either `None`, `infer`, or `toc`
page_authors                   : None  # Either `None` or `infer`
filename_title_split_character : '_'  # If inferring titles based on filename, splt on this character.

#######################################################################################
# Jupyter book extensions and additional features

# Bibliography and citation settings. See https://github.com/inukshuk/jekyll-scholar#configuration for options
# scholar:
#   style: apa

#######################################################################################
# Option to add a Goggle analytics tracking code

# Navigate to https://analytics.google.com, add a new property for your jupyter book and copy the tracking id here.
# google_analytics:
#   mytrackingcode: UA-52617120-7

#######################################################################################
# Jupyter book settings you probably don't need to change

content_folder_name       : "content"  # The folder where your raw content (notebooks/markdown files) are located
images_url                : "/assets/images" # Path to static image files
css_url                   : "/assets/css" # Path to static CSS files
js_url                    : "/assets/js" # Path to JS files
custom_static_url         : "/assets/custom" # Path to user's custom CSS/JS files


